// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui_helpers.h"

/**
 * @brief Set a bar value with the animation mode selected by an action ID.
 * @param target Bar object to update.
 * @param id Generated property selector.
 * @param val New bar value.
 * @return Nothing.
 * @note SquareLine-generated actions call this helper when changing a bar.
 */
void _ui_bar_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_BAR_PROPERTY_VALUE_WITH_ANIM) lv_bar_set_value(target, val, LV_ANIM_ON);
    if(id == _UI_BAR_PROPERTY_VALUE) lv_bar_set_value(target, val, LV_ANIM_OFF);
}

/**
 * @brief Change one basic position or size property of an LVGL object.
 * @param target Object to update.
 * @param id Generated selector for x, y, width, or height.
 * @param val New property value in pixels.
 * @return Nothing.
 * @note SquareLine-generated actions call this helper for basic geometry.
 */
void _ui_basic_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_BASIC_PROPERTY_POSITION_X) lv_obj_set_x(target, val);
    if(id == _UI_BASIC_PROPERTY_POSITION_Y) lv_obj_set_y(target, val);
    if(id == _UI_BASIC_PROPERTY_WIDTH) lv_obj_set_width(target, val);
    if(id == _UI_BASIC_PROPERTY_HEIGHT) lv_obj_set_height(target, val);
}

/**
 * @brief Select an item in a dropdown object.
 * @param target Dropdown object to update.
 * @param id Generated property selector.
 * @param val Zero-based option index.
 * @return Nothing.
 * @note SquareLine-generated actions call this helper for dropdown changes.
 */
void _ui_dropdown_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_DROPDOWN_PROPERTY_SELECTED) lv_dropdown_set_selected(target, val);
}

/**
 * @brief Replace the source displayed by an image object.
 * @param target Image object to update.
 * @param id Generated property selector.
 * @param val Pointer to the replacement image source.
 * @return Nothing.
 * @note SquareLine-generated actions call this helper for image changes.
 */
void _ui_image_set_property(lv_obj_t * target, int id, uint8_t * val)
{
    if(id == _UI_IMAGE_PROPERTY_IMAGE) lv_image_set_src(target, val);
}

/**
 * @brief Replace the text displayed by a label object.
 * @param target Label object to update.
 * @param id Generated property selector.
 * @param val Null-terminated replacement text.
 * @return Nothing.
 * @note SquareLine-generated actions call this helper for label changes.
 */
void _ui_label_set_property(lv_obj_t * target, int id, const char * val)
{
    if(id == _UI_LABEL_PROPERTY_TEXT) lv_label_set_text(target, val);
}

/**
 * @brief Select a roller item with the requested animation mode.
 * @param target Roller object to update.
 * @param id Generated property selector.
 * @param val Zero-based option index.
 * @return Nothing.
 * @note SquareLine-generated actions call this helper for roller changes.
 */
void _ui_roller_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM) lv_roller_set_selected(target, val, LV_ANIM_ON);
    if(id == _UI_ROLLER_PROPERTY_SELECTED) lv_roller_set_selected(target, val, LV_ANIM_OFF);
}

/**
 * @brief Set a slider value with the animation mode selected by an action ID.
 * @param target Slider object to update.
 * @param id Generated property selector.
 * @param val New slider value.
 * @return Nothing.
 * @note SquareLine-generated actions call this helper for slider changes.
 */
void _ui_slider_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM) lv_slider_set_value(target, val, LV_ANIM_ON);
    if(id == _UI_SLIDER_PROPERTY_VALUE) lv_slider_set_value(target, val, LV_ANIM_OFF);
}

/**
 * @brief Initialize a screen on demand and load it with an animation.
 * @param target Address of the generated screen reference.
 * @param fademode LVGL screen-load animation type.
 * @param spd Animation duration in milliseconds.
 * @param delay Delay before loading in milliseconds.
 * @param target_init Function that creates the screen when needed.
 * @return Nothing.
 * @note Generated navigation events call this helper during a screen change.
 */
void _ui_screen_change(lv_obj_t ** target, lv_screen_load_anim_t fademode, int spd, int delay,
                       void (*target_init)(void))
{
    if(*target == NULL)
        target_init();
    lv_screen_load_anim(*target, fademode, spd, delay, false);
}

/**
 * @brief Invoke a generated screen-destruction function when one is supplied.
 * @param target Screen-destruction callback, or NULL when no action is needed.
 * @return Nothing.
 * @note Generated navigation logic calls this after a screen is unloaded.
 */
void _ui_screen_delete(void (*target)(void))
{
    if(target != NULL) {
        target();
    }
}

/**
 * @brief Add an offset to an arc value and emit a value-changed event.
 * @param target Arc object to update.
 * @param val Signed increment applied to the current value.
 * @return Nothing.
 * @note Generated actions call this helper for relative arc adjustments.
 */
void _ui_arc_increment(lv_obj_t * target, int val)
{
    int old = lv_arc_get_value(target);
    lv_arc_set_value(target, old + val);
    lv_obj_send_event(target, LV_EVENT_VALUE_CHANGED, 0);
}

/**
 * @brief Add an offset to a bar value.
 * @param target Bar object to update.
 * @param val Signed increment applied to the current value.
 * @param anm LVGL animation enable value.
 * @return Nothing.
 * @note Generated actions call this helper for relative bar adjustments.
 */
void _ui_bar_increment(lv_obj_t * target, int val, int anm)
{
    int old = lv_bar_get_value(target);
    lv_bar_set_value(target, old + val, anm);
}

/**
 * @brief Add an offset to a slider and emit a value-changed event.
 * @param target Slider object to update.
 * @param val Signed increment applied to the current value.
 * @param anm LVGL animation enable value.
 * @return Nothing.
 * @note Generated actions call this helper for relative slider adjustments.
 */
void _ui_slider_increment(lv_obj_t * target, int val, int anm)
{
    int old = lv_slider_get_value(target);
    lv_slider_set_value(target, old + val, anm);
    lv_obj_send_event(target, LV_EVENT_VALUE_CHANGED, 0);
}

/**
 * @brief Associate an on-screen keyboard with a text area.
 * @param keyboard Keyboard object that will provide input.
 * @param textarea Text area that will receive the input.
 * @return Nothing.
 * @note Generated focus events call this when text entry begins.
 */
void _ui_keyboard_set_target(lv_obj_t * keyboard, lv_obj_t * textarea)
{
    lv_keyboard_set_textarea(keyboard, textarea);
}

/**
 * @brief Add, remove, or toggle one LVGL object flag.
 * @param target Object whose flags will change.
 * @param flag LVGL flag mask to modify.
 * @param value Generated add, remove, or toggle operation.
 * @return Nothing.
 * @note Generated actions call this helper when object behavior changes.
 */
void _ui_flag_modify(lv_obj_t * target, int32_t flag, int value)
{
    if(value == _UI_MODIFY_FLAG_TOGGLE) {
        if(lv_obj_has_flag(target, flag)) lv_obj_remove_flag(target, flag);
        else lv_obj_add_flag(target, flag);
    }
    else if(value == _UI_MODIFY_FLAG_ADD) lv_obj_add_flag(target, flag);
    else lv_obj_remove_flag(target, flag);
}

/**
 * @brief Add, remove, or toggle one LVGL object state.
 * @param target Object whose state will change.
 * @param state LVGL state mask to modify.
 * @param value Generated add, remove, or toggle operation.
 * @return Nothing.
 * @note Generated actions call this helper for interactive state changes.
 */
void _ui_state_modify(lv_obj_t * target, int32_t state, int value)
{
    if(value == _UI_MODIFY_STATE_TOGGLE) {
        if(lv_obj_has_state(target, state)) lv_obj_remove_state(target, state);
        else lv_obj_add_state(target, state);
    }
    else if(value == _UI_MODIFY_STATE_ADD) lv_obj_add_state(target, state);
    else lv_obj_remove_state(target, state);
}
/**
 * @brief Move a text-area cursor in one generated direction.
 * @param target Text area whose cursor will move.
 * @param val Generated direction selector.
 * @return Nothing.
 * @note Generated keyboard actions call this helper during text editing.
 */
void _ui_textarea_move_cursor(lv_obj_t * target, int val)

{

    if(val == UI_MOVE_CURSOR_UP) lv_textarea_cursor_up(target);
    if(val == UI_MOVE_CURSOR_RIGHT) lv_textarea_cursor_right(target);
    if(val == UI_MOVE_CURSOR_DOWN) lv_textarea_cursor_down(target);
    if(val == UI_MOVE_CURSOR_LEFT) lv_textarea_cursor_left(target);
    lv_obj_add_state(target, LV_STATE_FOCUSED);
}

typedef void (*screen_destroy_cb_t)(void);

/**
 * @brief Destroy a screen after LVGL reports that it has unloaded.
 * @param e Unload event carrying the destroy callback in user data.
 * @return Nothing.
 * @note LVGL calls this callback after a generated screen transition.
 */
void scr_unloaded_delete_cb(lv_event_t * e)

{

    // The originating screen supplies its matching destroy function.

    screen_destroy_cb_t destroy_cb = lv_event_get_user_data(e);
    if(destroy_cb) {

        destroy_cb();

    }

}

/**
 * @brief Set the overall opacity of an LVGL object.
 * @param target Object whose opacity will change.
 * @param val LVGL opacity value from transparent to fully opaque.
 * @return Nothing.
 * @note Generated actions call this helper for immediate opacity changes.
 */
void _ui_opacity_set(lv_obj_t * target, int val)
{
    lv_obj_set_style_opa(target, val, 0);
}

/**
 * @brief Release heap data attached to a completed animation.
 * @param a Animation whose generated user data will be freed.
 * @return Nothing.
 * @note LVGL calls this completion callback after a generated animation ends.
 */
void _ui_anim_callback_free_user_data(lv_anim_t * a)
{
    lv_free(a->user_data);
    a->user_data = NULL;
}

/**
 * @brief Apply an animation value to an object's horizontal position.
 * @param a Animation containing the target object in user data.
 * @param v New x position in pixels.
 * @return Nothing.
 * @note LVGL calls this for each step of a generated x-position animation.
 */
void _ui_anim_callback_set_x(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_x(usr->target, v);

}

/**
 * @brief Apply an animation value to an object's vertical position.
 * @param a Animation containing the target object in user data.
 * @param v New y position in pixels.
 * @return Nothing.
 * @note LVGL calls this for each step of a generated y-position animation.
 */
void _ui_anim_callback_set_y(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_y(usr->target, v);

}

/**
 * @brief Apply an animation value to an object's width.
 * @param a Animation containing the target object in user data.
 * @param v New width in pixels.
 * @return Nothing.
 * @note LVGL calls this for each step of a generated width animation.
 */
void _ui_anim_callback_set_width(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_width(usr->target, v);

}

/**
 * @brief Apply an animation value to an object's height.
 * @param a Animation containing the target object in user data.
 * @param v New height in pixels.
 * @return Nothing.
 * @note LVGL calls this for each step of a generated height animation.
 */
void _ui_anim_callback_set_height(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_height(usr->target, v);

}

/**
 * @brief Apply an animation value to an object's opacity.
 * @param a Animation containing the target object in user data.
 * @param v New LVGL opacity value.
 * @return Nothing.
 * @note LVGL calls this for each step of a generated opacity animation.
 */
void _ui_anim_callback_set_opacity(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_style_opa(usr->target, v, 0);

}

/**
 * @brief Apply an animation value to an image scale.
 * @param a Animation containing the image object in user data.
 * @param v New LVGL image scale value.
 * @return Nothing.
 * @note LVGL calls this for each step of a generated image-scale animation.
 */
void _ui_anim_callback_set_image_zoom(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_image_set_scale(usr->target, v);

}

/**
 * @brief Apply an animation value to an image rotation.
 * @param a Animation containing the image object in user data.
 * @param v New LVGL image rotation value.
 * @return Nothing.
 * @note LVGL calls this for each step of a generated rotation animation.
 */
void _ui_anim_callback_set_image_angle(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_image_set_rotation(usr->target, v);

}

/**
 * @brief Select a bounded image-set frame for an animation.
 * @param a Animation containing the image set and target in user data.
 * @param v Requested zero-based image frame.
 * @return Nothing.
 * @note LVGL calls this for each step of a generated frame animation.
 */
void _ui_anim_callback_set_image_frame(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    usr->val = v;

    if(v < 0) v = 0;
    if(v >= usr->imgset_size) v = usr->imgset_size - 1;
    lv_image_set_src(usr->target, usr->imgset[v]);
}

/**
 * @brief Read the animated object's aligned horizontal position.
 * @param a Animation containing the target object in user data.
 * @return Current x position in pixels.
 * @note LVGL calls this when a generated animation needs its starting value.
 */
int32_t _ui_anim_callback_get_x(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_x_aligned(usr->target);

}

/**
 * @brief Read the animated object's aligned vertical position.
 * @param a Animation containing the target object in user data.
 * @return Current y position in pixels.
 * @note LVGL calls this when a generated animation needs its starting value.
 */
int32_t _ui_anim_callback_get_y(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_y_aligned(usr->target);

}

/**
 * @brief Read the animated object's current width.
 * @param a Animation containing the target object in user data.
 * @return Current width in pixels.
 * @note LVGL calls this when a generated animation needs its starting value.
 */
int32_t _ui_anim_callback_get_width(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_width(usr->target);

}

/**
 * @brief Read the animated object's current height.
 * @param a Animation containing the target object in user data.
 * @return Current height in pixels.
 * @note LVGL calls this when a generated animation needs its starting value.
 */
int32_t _ui_anim_callback_get_height(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_height(usr->target);

}

/**
 * @brief Read the animated object's current opacity.
 * @param a Animation containing the target object in user data.
 * @return Current LVGL opacity value.
 * @note LVGL calls this when a generated animation needs its starting value.
 */
int32_t _ui_anim_callback_get_opacity(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_style_opa(usr->target, 0);

}

/**
 * @brief Read the animated image's current scale.
 * @param a Animation containing the image object in user data.
 * @return Current LVGL image scale value.
 * @note LVGL calls this when a generated animation needs its starting value.
 */
int32_t _ui_anim_callback_get_image_zoom(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_image_get_scale(usr->target);

}

/**
 * @brief Read the animated image's current rotation.
 * @param a Animation containing the image object in user data.
 * @return Current LVGL image rotation value.
 * @note LVGL calls this when a generated animation needs its starting value.
 */
int32_t _ui_anim_callback_get_image_angle(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_image_get_rotation(usr->target);

}

/**
 * @brief Read the generated image-set frame stored for an animation.
 * @param a Animation containing the image-set state in user data.
 * @return Current zero-based image frame.
 * @note LVGL calls this when a generated animation needs its starting value.
 */
int32_t _ui_anim_callback_get_image_frame(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return usr->val;

}

/**
 * @brief Format an arc value and display it in a label.
 * @param trg Label that receives the formatted text.
 * @param src Arc whose value is read.
 * @param prefix Text placed before the numeric value.
 * @param postfix Text placed after the numeric value.
 * @return Nothing.
 * @note Generated value-change events call this helper to refresh a label.
 */
void _ui_arc_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * prefix, const char * postfix)
{
    char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];

    lv_snprintf(buf, sizeof(buf), "%s%d%s", prefix, (int)lv_arc_get_value(src), postfix);

    lv_label_set_text(trg, buf);
}

/**
 * @brief Format a slider value and display it in a label.
 * @param trg Label that receives the formatted text.
 * @param src Slider whose value is read.
 * @param prefix Text placed before the numeric value.
 * @param postfix Text placed after the numeric value.
 * @return Nothing.
 * @note Generated value-change events call this helper to refresh a label.
 */
void _ui_slider_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * prefix, const char * postfix)
{
    char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];

    lv_snprintf(buf, sizeof(buf), "%s%d%s", prefix, (int)lv_slider_get_value(src), postfix);

    lv_label_set_text(trg, buf);
}

/**
 * @brief Select label text according to another object's checked state.
 * @param trg Label that receives the selected text.
 * @param src Object whose checked state is inspected.
 * @param txt_on Text displayed while the object is checked.
 * @param txt_off Text displayed while the object is not checked.
 * @return Nothing.
 * @note Generated state-change events call this helper to refresh a label.
 */
void _ui_checked_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * txt_on, const char * txt_off)
{
    if(lv_obj_has_state(src, LV_STATE_CHECKED)) lv_label_set_text(trg, txt_on);
    else lv_label_set_text(trg, txt_off);
}

/**
 * @brief Move a spinbox one step and emit a value-changed event.
 * @param target Spinbox object to update.
 * @param val Positive values increment; zero or negative values decrement.
 * @return Nothing.
 * @note Generated button events call this helper for spinbox controls.
 */
void _ui_spinbox_step(lv_obj_t * target, int val)

{

    if(val > 0) lv_spinbox_increment(target);

    else lv_spinbox_decrement(target);


    lv_obj_send_event(target, LV_EVENT_VALUE_CHANGED, 0);
}

/**
 * @brief Activate a generated theme when theme support is compiled in.
 * @param val Generated theme identifier.
 * @return Nothing.
 * @note Generated theme-selection events call this helper.
 */
void _ui_switch_theme(int val)

{

#ifdef UI_THEME_ACTIVE
    ui_theme_set(val);
#endif
}


