// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

// Receives the LED state selected by the two on-screen buttons.
extern int led;

// References the generated root screen object.
lv_obj_t * ui_Screen1 = NULL;

// References the on button displayed on Screen1.
lv_obj_t * ui_Button1 = NULL;

// References the off button displayed on Screen1.
lv_obj_t * ui_Button2 = NULL;

/**
 * @brief Keep an image button visually unchanged across interaction states.
 *
 * LVGL normally adds focus and pressed effects. Applying the same image,
 * geometry, and transparent decorations to every state prevents the button
 * from shifting or flashing while it is touched.
 *
 * @param button Button object whose styles will be normalized.
 * @param img_src Image source displayed on the button.
 * @return Nothing.
 * @note Screen1 initialization calls this once for each image button.
 */
static void keep_button_visual_stable(lv_obj_t * button, const void * img_src)
{
    lv_obj_remove_flag(button, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);

    const lv_style_selector_t selectors[] = {
        LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_PART_MAIN | LV_STATE_PRESSED,
        LV_PART_MAIN | LV_STATE_FOCUSED,
        LV_PART_MAIN | LV_STATE_PRESSED | LV_STATE_FOCUSED,
    };

    for(size_t i = 0; i < sizeof(selectors) / sizeof(selectors[0]); i++) {
        lv_style_selector_t selector = selectors[i];
        lv_obj_set_style_bg_color(button, lv_color_hex(0xFFFFFF), selector);
        lv_obj_set_style_bg_opa(button, LV_OPA_COVER, selector);
        lv_obj_set_style_bg_image_src(button, img_src, selector);
        lv_obj_set_style_bg_image_opa(button, LV_OPA_COVER, selector);
        lv_obj_set_style_border_opa(button, LV_OPA_TRANSP, selector);
        lv_obj_set_style_shadow_width(button, 0, selector);
        lv_obj_set_style_shadow_opa(button, LV_OPA_TRANSP, selector);
        lv_obj_set_style_transform_width(button, 0, selector);
        lv_obj_set_style_transform_height(button, 0, selector);
        lv_obj_set_style_translate_x(button, 0, selector);
        lv_obj_set_style_translate_y(button, 0, selector);
    }
}

/*---------------------------------------------------------------
 * Screen event callbacks
 * Each button updates the shared state consumed by app_main().
 *--------------------------------------------------------------*/

/**
 * @brief Request the external LED to turn on after a button click.
 * @param e LVGL event generated for the on button.
 * @return Nothing.
 * @note LVGL calls this function for events registered on ui_Button1.
 */
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        led = 1;
    }
}

/**
 * @brief Request the external LED to turn off after a button click.
 * @param e LVGL event generated for the off button.
 * @return Nothing.
 * @note LVGL calls this function for events registered on ui_Button2.
 */
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        led = 0;
    }
}

/*---------------------------------------------------------------
 * Screen object lifecycle
 * SquareLine creates widgets once and clears all references on deletion.
 *--------------------------------------------------------------*/

/**
 * @brief Build Screen1, its stable image buttons, and click callbacks.
 *
 * The button positions are offsets from the 480 x 272 screen center. Only
 * click events are registered because drag and focus events do not change LED
 * state in this lesson.
 *
 * @param None
 * @return Nothing.
 * @note ui_init() calls this function before loading Screen1.
 */
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen1, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Button1);
    lv_obj_set_width(ui_Button1, 62);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -98);
    lv_obj_set_y(ui_Button1, -2);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    keep_button_visual_stable(ui_Button1, &ui_img_on_png);

    ui_Button2 = lv_button_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Button2);
    lv_obj_set_width(ui_Button2, 62);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 88);
    lv_obj_set_y(ui_Button2, -2);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    keep_button_visual_stable(ui_Button2, &ui_img_off_png);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_CLICKED, NULL);

}

/**
 * @brief Delete Screen1 and clear every generated object reference.
 * @param None
 * @return Nothing.
 * @note ui_destroy() calls this function when unloading the generated UI.
 */
void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // Clearing references prevents later code from using deleted LVGL objects.
    ui_Screen1 = NULL;
    ui_Button1 = NULL;
    ui_Button2 = NULL;

}
