// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


/*---------------------------------------------------------------
 * Generated screen and resource declarations
 * Application code includes this header to access the SquareLine UI.
 *--------------------------------------------------------------*/

#include "ui_Screen1.h"

// References the generated object used for initial UI actions.
extern lv_obj_t * ui____initial_actions0;

// Describes the RGB565 images converted from the SquareLine project assets.
LV_IMG_DECLARE(ui_img_background_png); // assets/background.png
LV_IMG_DECLARE(ui_img_on_png);         // assets/on.png
LV_IMG_DECLARE(ui_img_off_png);        // assets/off.png

/**
 * @brief Create the generated UI and load its initial screen.
 * @param None
 * @return Nothing.
 * @note Call after LVGL has a registered display.
 */
void ui_init(void);

/**
 * @brief Release the generated screen objects.
 * @param None
 * @return Nothing.
 * @note Call when the generated UI is no longer needed.
 */
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
