// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

/*---------------------------------------------------------------
 * Screen1 object and callback declarations
 * These symbols are implemented in ui_Screen1.c.
 *--------------------------------------------------------------*/

/**
 * @brief Create Screen1 and all of its child widgets.
 * @param None
 * @return Nothing.
 * @note ui_init() calls this function before displaying Screen1.
 */
extern void ui_Screen1_screen_init(void);

/**
 * @brief Delete Screen1 and clear its object references.
 * @param None
 * @return Nothing.
 * @note ui_destroy() calls this function when releasing the UI.
 */
extern void ui_Screen1_screen_destroy(void);

// References the Screen1 root object while it exists.
extern lv_obj_t * ui_Screen1;

/**
 * @brief Handle click events from the on button.
 * @param e LVGL event associated with ui_Button1.
 * @return Nothing.
 * @note LVGL calls this through the registered button callback.
 */
extern void ui_event_Button1(lv_event_t * e);

// References the on button while Screen1 exists.
extern lv_obj_t * ui_Button1;

/**
 * @brief Handle click events from the off button.
 * @param e LVGL event associated with ui_Button2.
 * @return Nothing.
 * @note LVGL calls this through the registered button callback.
 */
extern void ui_event_Button2(lv_event_t * e);

// References the off button while Screen1 exists.
extern lv_obj_t * ui_Button2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
