// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

// Receives the LED state selected by the two on-screen buttons.
extern int led;

// References the generated root screen object.
lv_obj_t * ui_Screen1 = NULL;

// References the on button displayed on Screen1.
lv_obj_t * ui_Button1 = NULL;

// References the off button displayed on Screen1.
lv_obj_t * ui_Button2 = NULL;

/*---------------------------------------------------------------
 * Screen event callbacks
 * Each button updates the shared state consumed by the main loop.
 *--------------------------------------------------------------*/

/**
 * @brief Request the external LED to turn on after a button click.
 *
 * @param e LVGL event generated for the on button.
 * @return Nothing.
 * @note LVGL calls this function for events registered on ui_Button1.
 */
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        led = 1;
    }
}

/**
 * @brief Request the external LED to turn off after a button click.
 *
 * @param e LVGL event generated for the off button.
 * @return Nothing.
 * @note LVGL calls this function for events registered on ui_Button2.
 */
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        led = 0;
    }
}

/*---------------------------------------------------------------
 * Screen object lifecycle
 * SquareLine creates widgets once and clears all references on deletion.
 *--------------------------------------------------------------*/

/**
 * @brief Build Screen1, its image buttons, styles, and event callbacks.
 *
 * The button positions are offsets from the screen center. Both callbacks
 * receive all LVGL events and act only when the event code is clicked.
 *
 * @param None
 * @return Nothing.
 * @note ui_init() calls this function before loading Screen1.
 */
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen1, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 62);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -98);
    lv_obj_set_y(ui_Button1, -2);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button1, &ui_img_on_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 62);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 88);
    lv_obj_set_y(ui_Button2, -2);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button2, &ui_img_off_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}

/**
 * @brief Delete Screen1 and clear every generated object reference.
 *
 * @param None
 * @return Nothing.
 * @note ui_destroy() calls this function when unloading the generated UI.
 */
void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // Clearing references prevents later code from using deleted LVGL objects.
    ui_Screen1 = NULL;
    ui_Button1 = NULL;
    ui_Button2 = NULL;

}
