esphome:
  name: 43-hometest
  friendly_name: 4.3_hometest
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio
esp32:
  board: adafruit_feather_esp32s3
  framework:
    type: esp-idf
    #version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: quad
  speed: 80MHz
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "TRGX46JfxstTQHNogjjGacfvu7dLEt5TGLEppnF/Bb4="

ota:
  password: "9a8c90821103cbe8a487aed8f698f14f"

wifi:
  ssid: "yanfa_software"
  password: "yanfa-123456"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "43-Hometest Fallback Hotspot"
    password: "6ORkWEblBuOh"

captive_portal:
#引入第三方LVGL库
external_components:
  - source:
      type: git
      url: https://github.com/clydebarrow/esphome
      ref: fd15094c0860df23d532881df36cfd16c7da1091 #previous commit - wont be needed in the future
    components: [ lvgl ]
#设置背光引脚
output:
  - platform: ledc
    pin:
      number: GPIO2
    id: backlight_output
#打开背光
light:
  - platform: monochromatic
    output: backlight_output
    name: LCD Backlight
    id: led
    restore_mode: ALWAYS_ON
    default_transition_length: 0s
#引入UI素材
image:
  - file: "light.png"
    id: on_light
    resize: 50x50
    type: RGB565
  - file: "small_hum.png"
    id: small_hum
    resize: 50x75
    type: RGB565
  - file: "small_logo.png"
    id: small_logo
    resize: 250x52
    type: RGB565
  - file: "small_off.png"
    id: small_off
    resize: 50x75
    type: RGB565
  - file: "small_temp.png"
    id: small_temp
    resize: 50x75
    type: RGB565
  - file: "no_light.png"
    id: no_light
    resize: 50x50
    type: RGB565
#设置i2c引脚
i2c:
  sda: 37
  scl: 38
#设置屏幕配置
display:
  - platform: rpi_dpi_rgb
    id: main_display
    color_order: RGB
    invert_colors: True
    update_interval: never
    auto_clear_enabled: false # takes 2.8 seconds to clear the display
    dimensions:
      width: 480
      height: 272
    de_pin: 40
    hsync_pin: 39
    vsync_pin: 41
    pclk_pin: 42
    pclk_frequency: 4MHz
    hsync_pulse_width: 4
    hsync_front_porch: 8
    hsync_back_porch: 43
    vsync_pulse_width: 4
    vsync_front_porch: 8
    vsync_back_porch: 12
    data_pins:
      red:
        - 45        #r1
        - 48        #r2
        - 47        #r3
        - 21        #r4
        - 14        #r5
      green:
        - 5         #g0
        - 6         #g1
        - 7         #g2
        - 15        #g3
        - 16        #g4
        - 4         #g5
      blue:
        - 8         #b1
        - 3         #b2
        - 46        #b3
        - 9         #b4
        - 1         #b5
#设置tsl2561传感器，DHT22温湿度传感器
sensor:
  - platform: tsl2561
    name: "TSL2561 Ambient Light"
    id: TSL2561
    address: 0x29
    update_interval: 2s
  - platform: dht
    pin: 18
    temperature:
      name: "HMI-24 Temperature"
      id: temperature24
    humidity:
      id: humidity24
      name: "HMI-24 Humidity"
    update_interval: 5s
    model: DHT22

time:
  - platform: homeassistant
    id: time_comp


#使用LVGL显示UI画面
lvgl:
  log_level: INFO
  color_depth: 16
  bg_color: 0xFFFFFF
  text_font: unscii_8
  align: center
  style_definitions:
    - id: date_style
      text_font: unscii_8
      align: center
      text_color: 0x000000
      bg_opa: cover
      radius: 4
      pad_all: 2
  widgets:
      - img:          
          src: small_logo
          id: lvgl_logo
          x: 100
          y: 20
      - img:          
          src: on_light
          id: lvgl_light
          x: 100
          y: 150
      - img:          
          src: small_hum
          id: lvgl_hum
          x: 240
          y: 130
      - img:          
          src: small_temp
          id: lvgl_temp
          x: 380
          y: 130
      - label:
          id : tsl
          text_font: montserrat_24
          text:
             format: "%.0f"
             args: ['id(TSL2561).state']
          x: 100
          y: 200
      - label:
          id : hum
          text_font: montserrat_24
          text:
             format: "%.0f"
             args: ['id(humidity24).state']
          x: 240
          y: 200
      - label:
          id : tem
          text_font: montserrat_24
          text:
             format: "%.0f"
             args: ['id(temperature24).state']
          x: 380
          y: 200
#设置一个定时器定时更新UI数据
interval:
  - interval: 1s
    then: 
      - lvgl.label.update:
          id: tsl
          text:
             format: "%.1f"
             args: ['id(TSL2561).state']
      - lvgl.label.update:
          id: hum
          text:
             format: "%.1f"
             args: ['id(humidity24).state']
      - lvgl.label.update:
          id: tem
          text:
             format: "%.1f"
             args: ['id(temperature24).state']