#include <lvgl.h>
#include <SPI.h>
#include <Arduino_GFX_Library.h>
#include "ui.h"

/******************************************************************************/

#define TFT_BL 2
#define GFX_BL DF_GFX_BL // default backlight pin, you may replace DF_GFX_BL to actual backlight pin

#if defined(DISPLAY_DEV_KIT)
Arduino_GFX *lcd = create_default_Arduino_GFX();
#else /* !defined(DISPLAY_DEV_KIT) */

// Stores the state requested by the on-screen LED buttons.
int led;

// Reuses the board's standard SPI controller for touch communication.
SPIClass& spi = SPI;

/*---------------------------------------------------------------
 * RGB display hardware
 * Arduino GFX generates the RGB timing signals for the NV3047 panel.
 *--------------------------------------------------------------*/
Arduino_ESP32RGBPanel *bus = new Arduino_ESP32RGBPanel(
  // RGB control pins.
  40 /* DE */, 41 /* VSYNC */, 39 /* HSYNC */, 42 /* PCLK */,
  // RGB565 red, green, and blue data pins.
  45 /* R0 */, 48 /* R1 */, 47 /* R2 */, 21 /* R3 */, 14 /* R4 */,
  5 /* G0 */, 6 /* G1 */, 7 /* G2 */, 15 /* G3 */, 16 /* G4 */, 4 /* G5 */,
  8 /* B0 */, 3 /* B1 */, 46 /* B2 */, 9 /* B3 */, 1 /* B4 */,
  // Horizontal and vertical synchronization timing.
  0 /* hsync_polarity */, 8 /* hsync_front_porch */, 4 /* hsync_pulse_width */, 43 /* hsync_back_porch */,
  0 /* vsync_polarity */, 8 /* vsync_front_porch */, 4 /* vsync_pulse_width */, 12 /* vsync_back_porch */,
  // Pixel-clock polarity, speed, byte order, and bounce-buffer size.
  1 /* pclk_active_neg */, 9000000 /* prefer_speed */, false /* useBigEndian */,
  0 /* de_idle_high */, 0 /* pclk_idle_high */, 480 /* bounce_buffer_size_px */
);

// Exposes the 480 x 272 panel through the common Arduino GFX interface.
Arduino_RGB_Display *lcd = new Arduino_RGB_Display(
  480 /* width */, 272 /* height */, bus, 0 /* rotation */, false /* auto_flush */
);

#endif /* !defined(DISPLAY_DEV_KIT) */

/*******************************************************************************
   Please config the touch panel in touch.h
 ******************************************************************************/
#include "touch.h"

/* Stores the display dimensions reported by Arduino GFX. */
static uint32_t screenWidth;
static uint32_t screenHeight;

// Stores one partial LVGL render buffer. A smaller buffer saves RAM,
// while LVGL refreshes the screen in several rectangular pieces.
static lv_color_t disp_draw_buf[480 * 272 / 8];

/**
 * @brief Copy one rendered LVGL area to the RGB LCD.
 *
 * LVGL calls this function whenever a part of the UI needs to be redrawn.
 * The callback sends RGB565 pixels to Arduino GFX and then notifies LVGL
 * that the buffer can be reused.
 *
 * @param disp LVGL display object that requested the refresh.
 * @param area Rectangle area that needs to be updated.
 * @param px_map Pixel buffer generated by LVGL.
 * @return None.
 * @note Called automatically by LVGL after registration in setup().
 */
void my_disp_flush(lv_display_t *disp, const lv_area_t *area, uint8_t *px_map)
{
  // Convert the LVGL area into width and height values required by Arduino GFX.
  uint32_t w = lv_area_get_width(area);
  uint32_t h = lv_area_get_height(area);

  lcd->draw16bitRGBBitmap(area->x1, area->y1, reinterpret_cast<uint16_t *>(px_map), w, h);

  lv_display_flush_ready(disp);
}

/**
 * @brief Provide the latest touch state and calibrated point to LVGL.
 *
 * LVGL calls this reader from its timer processing. The callback reports a
 * press only when the touch helper has a valid sample and reports release
 * otherwise, so button interactions can complete normally.
 *
 * @param indev LVGL input device requesting a sample.
 * @param data Output structure that receives state and coordinates.
 * @return None.
 * @note Called repeatedly while lv_timer_handler() processes input devices.
 */
void my_touchpad_read(lv_indev_t *indev, lv_indev_data_t *data)
{
  LV_UNUSED(indev);
  if (touch_has_signal())
  {
    if (touch_touched())
    {
      // Submit the latest calibrated point as a pressed LVGL pointer sample.
      data->state = LV_INDEV_STATE_PRESSED;

      /*Set the coordinates*/
      data->point.x = touch_last_x;
      data->point.y = touch_last_y;
      Serial.print( "Data x :" );
      Serial.println( touch_last_x );

      Serial.print( "Data y :" );
      Serial.println( touch_last_y );
    }
    else if (touch_released())
    {
      // Tell LVGL that the pointer was released when no new point is present.
      data->state = LV_INDEV_STATE_RELEASED;
    }
  }
  else
  {
    // No interrupt signal means there is no active touch.
    data->state = LV_INDEV_STATE_RELEASED;
  }
}

/**
 * @brief Supply Arduino millisecond time to LVGL.
 *
 * @param None.
 * @return Current uptime in milliseconds.
 * @note LVGL calls this callback whenever it needs the current tick count.
 */
uint32_t millis_cb(void)
{
  return millis();
}

/**
 * @brief Initialize the LCD, touch controller, LVGL devices, and UI.
 *
 * Hardware is initialized before LVGL callbacks are registered. The
 * SquareLine-generated screen is created only after display and input devices
 * are ready.
 *
 * @param None.
 * @return None.
 * @note Arduino calls setup() once after reset.
 */
void setup()
{
  Serial.begin( 115200 );
  pinMode(38, OUTPUT);
  digitalWrite(38, LOW);
  pinMode(0, OUTPUT);//TOUCH-CS

  lv_init();
  lv_tick_set_cb(millis_cb);

  // Initialize the LCD hardware before creating LVGL display objects.
  lcd->begin();
  lcd->setTextSize(2);
  lcd->fillScreen(RGB565_BLACK);

  // Initialize the XPT2046 controller and its SPI bus.
  touch_init();
  //setTouch(calData);
  screenWidth = lcd->width();
  screenHeight = lcd->height();

  // Register the LCD flush callback and partial render buffer with LVGL.
  lv_display_t *disp = lv_display_create(screenWidth, screenHeight);
  lv_display_set_flush_cb(disp, my_disp_flush);
  lv_display_set_buffers(disp, disp_draw_buf, NULL, sizeof(disp_draw_buf), LV_DISPLAY_RENDER_MODE_PARTIAL);

  // Register the touch panel as a pointer device for LVGL buttons.
  lv_indev_t *indev = lv_indev_create();
  lv_indev_set_type(indev, LV_INDEV_TYPE_POINTER);
  lv_indev_set_read_cb(indev, my_touchpad_read);

  delay(300);
#ifdef TFT_BL
  pinMode(TFT_BL, OUTPUT);
  digitalWrite(TFT_BL, HIGH);
#endif
  // Build the background, image buttons, and events exported by SquareLine.
  ui_init();
  
  lv_timer_handler();
}

/**
 * @brief Service LVGL and apply the requested LED state.
 *
 * The timer handler keeps rendering and touch processing active. The shared
 * state written by the UI callbacks is then reflected on GPIO 38.
 *
 * @param None.
 * @return None.
 * @note Arduino calls loop() repeatedly after setup() completes.
 */
void loop()
{
  // Service LVGL timers so display refresh and touch processing continue.
  lv_timer_handler();

  // Apply the state selected by the on-screen buttons to GPIO 38.
  if(led == 1)
    digitalWrite(38, HIGH);
  if(led == 0)
    digitalWrite(38, LOW);

  delay(50);
}

  
