// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

extern int led;

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Button2 = NULL;

/**
 * @brief Keep an image button visually stable in every interaction state.
 *
 * Applying identical image, geometry, and transparent decorations to each
 * state prevents the button from shifting or flashing while it is touched.
 *
 * @param button Button object whose styles will be normalized.
 * @param img_src Image source displayed on the button.
 * @return None.
 * @note Screen1 initialization calls this once for each image button.
 */
static void keep_button_visual_stable(lv_obj_t * button, const void * img_src)
{
    lv_obj_remove_flag(button, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);

    const lv_style_selector_t selectors[] = {
        LV_PART_MAIN | LV_STATE_DEFAULT,
        LV_PART_MAIN | LV_STATE_PRESSED,
        LV_PART_MAIN | LV_STATE_FOCUSED,
        LV_PART_MAIN | LV_STATE_PRESSED | LV_STATE_FOCUSED,
    };

    for(size_t i = 0; i < sizeof(selectors) / sizeof(selectors[0]); i++) {
        lv_style_selector_t selector = selectors[i];
        lv_obj_set_style_bg_color(button, lv_color_hex(0xFFFFFF), selector);
        lv_obj_set_style_bg_opa(button, LV_OPA_COVER, selector);
        lv_obj_set_style_bg_image_src(button, img_src, selector);
        lv_obj_set_style_bg_image_opa(button, LV_OPA_COVER, selector);
        lv_obj_set_style_border_opa(button, LV_OPA_TRANSP, selector);
        lv_obj_set_style_shadow_width(button, 0, selector);
        lv_obj_set_style_shadow_opa(button, LV_OPA_TRANSP, selector);
        lv_obj_set_style_transform_width(button, 0, selector);
        lv_obj_set_style_transform_height(button, 0, selector);
        lv_obj_set_style_translate_x(button, 0, selector);
        lv_obj_set_style_translate_y(button, 0, selector);
    }
}

/**
 * @brief Request the external LED to turn on after a button click.
 *
 * The callback records the requested state; loop() performs the GPIO write.
 *
 * @param e LVGL event generated for the on button.
 * @return None.
 * @note LVGL calls this function when Button1 receives a click event.
 */
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // The main loop applies this shared state to GPIO 38.
        led = 1;
    }
}

/**
 * @brief Request the external LED to turn off after a button click.
 *
 * The callback clears the shared state; loop() performs the GPIO write.
 *
 * @param e LVGL event generated for the off button.
 * @return None.
 * @note LVGL calls this function when Button2 receives a click event.
 */
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // Clearing the shared state turns GPIO 38 off in loop().
        led = 0;
    }
}

/**
 * @brief Build Screen1 and attach its image buttons and click callbacks.
 *
 * @param None.
 * @return None.
 * @note ui_init() calls this once when loading the generated interface.
 */
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen1, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Button1);
    lv_obj_set_width(ui_Button1, 62);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -98);
    lv_obj_set_y(ui_Button1, -2);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    keep_button_visual_stable(ui_Button1, &ui_img_on_png);

    ui_Button2 = lv_button_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Button2);
    lv_obj_set_width(ui_Button2, 62);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 88);
    lv_obj_set_y(ui_Button2, -2);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    keep_button_visual_stable(ui_Button2, &ui_img_off_png);

    // Only click events change the LED state; other LVGL events are ignored.
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_CLICKED, NULL);

}

/**
 * @brief Delete Screen1 and clear generated object references.
 *
 * @param None.
 * @return None.
 * @note ui_destroy() calls this when unloading the generated interface.
 */
void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Button1 = NULL;
    ui_Button2 = NULL;

}
