# Board: Generic ESP32-S3 Board (Generic)
# Definition: definitions/boards/generic-esp32s3/manifest.yaml

esphome:
  name: basic-hmi-43inch
  friendly_name: Basic_HMI_4.3inch
  platformio_options:
    build_flags:
      - -DBOARD_HAS_PSRAM
      - -I$PROJECT_PACKAGES_DIR/framework-espidf/components/esp_lcd/include
      - -I$PROJECT_PACKAGES_DIR/framework-espidf/components/esp_lcd/rgb/include
      - -I/data/cache/platformio/packages/framework-espidf/components/esp_lcd/include
      - -I/data/cache/platformio/packages/framework-espidf/components/esp_lcd/rgb/include
    board_build.flash_mode: dio

external_components:
  - source:
      type: local
      path: esphome_external_components
    components: [crowpanel_ui]
    
esp32:
  variant: esp32s3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: quad
  speed: 80MHz

logger:
  level: VERY_VERBOSE

api:
  encryption:
    key: "k9uXFsr2o1yfApE908Gsxf/m5jj4Mk82kYL9hMUM8d8="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: Basic_HMI_4.3in Fallback Hotspot
    password: "tTJ8UdcmAoUO"

captive_portal:

output:
  - platform: ledc
    pin: GPIO2
    id: backlight_output
    frequency: 1000Hz

light:
  - platform: monochromatic
    output: backlight_output
    name: LCD Backlight
    id: lcd_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 0s

switch:
  - platform: template
    name: "LED Control"
    id: led_switch
    lambda: return id(main_rgb_panel).get_light_state();
    turn_on_action:
      - lambda: id(main_rgb_panel).set_light_state(true);
    turn_off_action:
      - lambda: id(main_rgb_panel).set_light_state(false);

sensor:
  - platform: template
    name: "4.3 Temperature"
    id: temperature43
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    update_interval: 5s
    lambda: return id(main_rgb_panel).get_temperature();
  - platform: template
    name: "4.3 Humidity"
    id: humidity43
    device_class: humidity
    state_class: measurement
    unit_of_measurement: "%"
    accuracy_decimals: 1
    update_interval: 5s
    lambda: return id(main_rgb_panel).get_humidity();

crowpanel_ui:
  id: main_rgb_panel

